### ISSUE TITLE
get_parameters() missing 1 required positional argument: 'cls'

### ISSUE THREAD

**Issue by Abolfazl74** [aledipa/Free-GPT4-WEB-API#39]
Getting the following error after sending request with default settings on bing:
[2024-03-24 22:16:54,169] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 254, in __call__
    return call_result.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/Free-GPT4-WEB-API-main/src/FreeGPT4_Server.py", line 146, in index
    print(PROVIDERS[args.provider].params)  # supported args
  File "/usr/local/lib/python3.10/dist-packages/g4f/providers/base_provider.py", line 98, in params
    for name, param in cls.get_parameters().items():
TypeError: AbstractProvider.get_parameters() missing 1 required positional argument: 'cls'

**Comment by aledipa** [comment]
> Getting the following error after sending request with default settings on bing: [2024-03-24 22:16:54,169] ERROR in app: Exception on / [GET] Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2077, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1525, in full_dispatch_request rv = self.handle_user_exception(e) File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1523, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1509, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 254, in **call** return call_result.result() File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result return self.__get_result() File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result raise self._exception File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 331, in main_wrap result = await self.awaitable(*args, **kwargs) File "/Free-GPT4-WEB-API-main/src/FreeGPT4_Server.py", line 146, in index print(PROVIDERS[args.provider].params) # supported args File "/usr/local/lib/python3.10/dist-packages/g4f/providers/base_provider.py", line 98, in params for name, param in cls.get_parameters().items(): TypeError: AbstractProvider.get_parameters() missing 1 required positional argument: 'cls'

This issue has been fixed with [this commit](https://github.com/aledipa/Free-GPT4-WEB-API/commit/fabe255af3425afc629b8366c43b55d118c6b2e7), thanks for reporting!
