### ISSUE TITLE
500 error for gui

### ISSUE THREAD

**Issue by MH140000** [aledipa/Free-GPT4-WEB-API#57]
ERROR:FreeGPT4_Server:Exception on /login [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 254, in __call__
    return call_result.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/root/Free-GPT4-WEB-API/src/FreeGPT4_Server.py", line 475, in login
    return render_template("login.html", **locals())
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.10/dist-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/root/Free-GPT4-WEB-API/src/templates/login.html", line 38, in template
    <script src="{{ url_for('static', filename='js/script.js') }}" type="text/javascript"></script>
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'static'

**Comment by 18goldr** [comment]
Ya I'm getting the same issue:
```
Traceback (most recent call last):
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/venv/lib/python3.12/site-packages/asgiref/sync.py", line 254, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/venv/lib/python3.12/site-packages/asgiref/sync.py", line 331, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/src/FreeGPT4_Server.py", line 475, in login
    return render_template("login.html", **locals())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/venv/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/venv/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/venv/lib/python3.12/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/venv/lib/python3.12/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/venv/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/Caspian/Work/Free-GPT4-WEB-API/src/templates/login.html", line 38, in template
    <script src="{{ url_for('static', filename='js/script.js') }}" type="text/javascript"></script>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'static'
INFO:werkzeug:172.27.160.1 - - [01/Nov/2024 16:29:57] "GET /login HTTP/1.1" 500 -
```

**Comment by aledipa** [comment]
Thank you for reporting, I'll try to fix this issue as soon as possible

**Comment by 18goldr** [comment]
I fixed it. There was a missing `'` on line 12.

I changed the line from:
`<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon(Nicoladipa).png) }}" type="image/x-icon">`

to

`<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon(Nicoladipa).png') }}" type="image/x-icon">`

**Comment by aledipa** [comment]
> I fixed it @aledipa. There was a missing `'` on line 12 in `src/templates/login.html`.
> 
> I changed the line from: `<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon(Nicoladipa).png) }}" type="image/x-icon">`
> 
> to
> 
> `<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon(Nicoladipa).png') }}" type="image/x-icon">`

Got it, thank you, you can open a pull request in order to get the credit for the contribution since you found and fixed this issue

**Comment by aledipa** [comment]
> Hi, sorry, I did not see your reply. Would you like me to still submit a pull request?
> 
> 

Don't worry, the issue has been already fixed and you were mentioned as contributor in the related release
