### ISSUE TITLE
unavailable

### ISSUE THREAD

**Issue by thb10086** [aledipa/Free-GPT4-WEB-API#8]
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
![image](https://github.com/aledipa/Free-GPT4-WEB-API/assets/68690699/fbae07ce-56e3-42eb-8e4f-f571d66308de)
![image](https://github.com/aledipa/Free-GPT4-WEB-API/assets/68690699/24be213c-495a-4a9c-b60e-974f74cfb81e)

**Comment by urosch** [comment]
same here
free-gpt4-web-api-api-1  |         FreeGPT4 Web API - A Web API for GPT-4 (Using BingAI)
free-gpt4-web-api-api-1  |         Repo: github.com/aledipa/FreeGPT4-WEB-API
free-gpt4-web-api-api-1  |         By: Alessandro Di Pasquale
free-gpt4-web-api-api-1  | 
free-gpt4-web-api-api-1  |         EdgeGPT Credits: github.com/acheong08/EdgeGPT
free-gpt4-web-api-api-1  |     
free-gpt4-web-api-api-1  |  * Serving Flask app 'FreeGPT4_Server'
free-gpt4-web-api-api-1  |  * Debug mode: off
free-gpt4-web-api-api-1  | WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
free-gpt4-web-api-api-1  |  * Running on all addresses (0.0.0.0)
free-gpt4-web-api-api-1  |  * Running on http://127.0.0.1:5500
free-gpt4-web-api-api-1  |  * Running on http://172.20.0.2:5500
free-gpt4-web-api-api-1  | Press CTRL+C to quit
free-gpt4-web-api-api-1  | 172.20.0.1 - - [29/Jun/2023 06:58:07] "GET / HTTP/1.1" 200 -
free-gpt4-web-api-api-1  | 172.20.0.1 - - [29/Jun/2023 06:58:07] "GET /favicon.ico HTTP/1.1" 404 -
free-gpt4-web-api-api-1  | 172.20.0.1 - - [29/Jun/2023 06:59:33] "HEAD /?text=what%20is%20the%20number%20of%20continents%20on%20earth HTTP/1.1" 400 -
free-gpt4-web-api-api-1  | [2023-06-29 07:00:10,052] ERROR in app: Exception on / [GET]
free-gpt4-web-api-api-1  | Traceback (most recent call last):
free-gpt4-web-api-api-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
free-gpt4-web-api-api-1  |     response = self.full_dispatch_request()
free-gpt4-web-api-api-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
free-gpt4-web-api-api-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
free-gpt4-web-api-api-1  |     rv = self.handle_user_exception(e)
free-gpt4-web-api-api-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
free-gpt4-web-api-api-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
free-gpt4-web-api-api-1  |     rv = self.dispatch_request()
free-gpt4-web-api-api-1  |          ^^^^^^^^^^^^^^^^^^^^^^^
free-gpt4-web-api-api-1  |   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
free-gpt4-web-api-api-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
free-gpt4-web-api-api-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
free-gpt4-web-api-api-1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 277, in __call__
free-gpt4-web-api-api-1  |     return call_result.result()
free-gpt4-web-api-api-1  |            ^^^^^^^^^^^^^^^^^^^^
free-gpt4-web-api-api-1  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
free-gpt4-web-api-api-1  |     return self.__get_result()
free-gpt4-web-api-api-1  |            ^^^^^^^^^^^^^^^^^^^
free-gpt4-web-api-api-1  |   File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
free-gpt4-web-api-api-1  |     raise self._exception
free-gpt4-web-api-api-1  |   File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 353, in main_wrap
free-gpt4-web-api-api-1  |     result = await self.awaitable(*args, **kwargs)
free-gpt4-web-api-api-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
free-gpt4-web-api-api-1  |   File "/app/FreeGPT4_Server.py", line 47, in index
free-gpt4-web-api-api-1  |     (
free-gpt4-web-api-api-1  | KeyError: 'text'
free-gpt4-web-api-api-1  | 172.20.0.1 - - [29/Jun/2023 07:00:10] "GET /?text=what%20is%20the%20number%20of%20continents%20on%20earth HTTP/1.1" 500 -

**Comment by aledipa** [comment]
Hi, I think the problem is due to the request limit that Microsoft has set for the chat mode when using it as non-logged in (as you can see from the following image)
<img width="1624" alt="Screenshot" src="https://github.com/aledipa/Free-GPT4-WEB-API/assets/51910404/14525308-b208-4db8-a489-2af4b4acdd48">
which consists of about 5 questions. However, there is a solution to this issue: use the API with the cookies argument so that you are recognised as logged in and then have a chat limit of about 30 queries.
This would do the trick and it shouldn't even cause any further troubles when the limit is exceeded.
I hope this can help you, please let me know if there are any other problems.

**Comment by urosch** [comment]
I'm already using the cookies.json and I got this error on first request already.

**Comment by aledipa** [comment]
I did some tests and the [latest commit](https://github.com/aledipa/Free-GPT4-WEB-API/commit/662ed673d24266020b087300989a6e4f4b6fa688) should have solved the issue.

**Comment by urosch** [comment]
still receive:  Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
using latest commit and json cookies
